version: 2

builds:
  - main: .
    binary: nokey
    ldflags:
      - -s -w
      - -X github.com/nokey-ai/nokey/internal/version.Version={{.Version}}
      - -X github.com/nokey-ai/nokey/internal/version.Commit={{.ShortCommit}}
      - -X github.com/nokey-ai/nokey/internal/version.Date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
